### ISSUE TITLE
`jsconfig.json` is not supported

### ISSUE THREAD

**Issue by JounQin** [ShenQingchuan/tsc-err-dirs#5]
https://github.com/ShenQingchuan/tsc-err-dirs/blob/15cda49e4b467830c3a11b5c02dca5275e079074/src/ts-errs-map.ts#L100

**Comment by ShenQingchuan** [comment]
I'm pretty doubting why we need to support `jsconfig.json` in tsc checking.
`jsconfig.json` seems to have nothing to do with `tsc`.

**Comment by JounQin** [comment]
> jsconfig.json seems to have nothing to do with tsc.

I don't understand why? TSC can work with `jsdoc` based type checking very well.

**Comment by tjx666** [comment]
why not just support pass -p option to specify config file. This is my project structure:

<img width="302" alt="image" src="https://github.com/ShenQingchuan/tsc-err-dirs/assets/41773861/684a7a2f-9f07-42f1-ba6b-6df69d1d1707">
