### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'emitDeclarationOnly')

### ISSUE THREAD

**Issue by tjx666** [ShenQingchuan/tsc-err-dirs#6]
reproduce:

1. `git clone https://github.com/tjx666/tsc-err-dirs-issue`
2. `pnpm install`
3. `cd app`
4. `vue-tsc --noEmit` works fine
5. `tsc-err-dirs --engine vue-tsc .` show error: `TypeError: Cannot set properties of undefined (setting 'emitDeclarationOnly')`

```node
❯ tsc-err-dirs --engine vue-tsc .


 _                                   _ _          
| |_ ___  ___    ___ _ __ _ __    __| (_)_ __ ___ 
| __/ __|/ __|  / _ \ '__| '__|  / _` | | '__/ __|
| |_\__ \ (__  |  __/ |  | |    | (_| | | |  \__ \
 \__|___/\___|  \___|_|  |_|     \__,_|_|_|  |___/  [version: v0.0.22]
  
Failed to process `tsconfig.json`
TypeError: Cannot set properties of undefined (setting 'emitDeclarationOnly')
```

![image](https://github.com/ShenQingchuan/tsc-err-dirs/assets/41773861/65cf0a8e-30e1-4df8-a54a-672e42359ffc)

**Comment by ShenQingchuan** [comment]
Hi, glad to recieve your response.

After cloned your mini reproduction repo, I found that the `package.json` only contains `"@tools/tsconfig": "workspace:*"` this one `devDependencies`, and I couldn't start my `pnpm install`.

Maybe there's something lost when you extracted out these file from your real project?

**Comment by tjx666** [comment]
<img width="1440" alt="image" src="https://github.com/ShenQingchuan/tsc-err-dirs/assets/41773861/0f8b37b0-749a-4906-98e4-c64b97420d10">

**Comment by tjx666** [comment]
Sorry late response, I update the repo code.

**Comment by ShenQingchuan** [comment]
@tjx666 

You can try on v0.0.23

**Comment by tjx666** [comment]
一直卡在 `✔ tsc compiling finished.`

<img width="813" alt="image" src="https://github.com/ShenQingchuan/tsc-err-dirs/assets/41773861/b2ecf75b-4731-49cb-b514-ca05093019ce">

```node
❯ vue-tsc --noEmit --pretty false
src/main.ts(13,1): error TS2322: Type 'string' is not assignable to type 'number'.
```
